TrajectoryPlannerROS:
  max_vel_x: 1
  min_vel_x: 0.1
  max_vel_theta: 0.8
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 2
  acc_lim_x: 0.7
  acc_lim_y: 0.7

  holonomic_robot: true

  meter_scoring: false

  dwa: false

  sim_time: 2

  occdist_scale: .002
  
  yaw_goal_tolerance: 0.2

  

