// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_planner.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "local_planner.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace roborts_local_planner {

namespace {

const ::google::protobuf::Descriptor* LocalAlgorithms_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LocalAlgorithms_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_local_5fplanner_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_local_5fplanner_2eproto() {
  protobuf_AddDesc_local_5fplanner_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "local_planner.proto");
  GOOGLE_CHECK(file != NULL);
  LocalAlgorithms_descriptor_ = file->message_type(0);
  static const int LocalAlgorithms_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, selected_algorithm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, frequency_),
  };
  LocalAlgorithms_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LocalAlgorithms_descriptor_,
      LocalAlgorithms::default_instance_,
      LocalAlgorithms_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, _has_bits_[0]),
      -1,
      -1,
      sizeof(LocalAlgorithms),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_local_5fplanner_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LocalAlgorithms_descriptor_, &LocalAlgorithms::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_local_5fplanner_2eproto() {
  delete LocalAlgorithms::default_instance_;
  delete LocalAlgorithms_reflection_;
}

void protobuf_AddDesc_local_5fplanner_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_local_5fplanner_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023local_planner.proto\022\025roborts_local_pla"
    "nner\"N\n\017LocalAlgorithms\022\014\n\004name\030\001 \003(\t\022\032\n"
    "\022selected_algorithm\030\002 \001(\t\022\021\n\tfrequency\030\003"
    " \001(\001", 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "local_planner.proto", &protobuf_RegisterTypes);
  LocalAlgorithms::default_instance_ = new LocalAlgorithms();
  LocalAlgorithms::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_local_5fplanner_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_local_5fplanner_2eproto {
  StaticDescriptorInitializer_local_5fplanner_2eproto() {
    protobuf_AddDesc_local_5fplanner_2eproto();
  }
} static_descriptor_initializer_local_5fplanner_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LocalAlgorithms::kNameFieldNumber;
const int LocalAlgorithms::kSelectedAlgorithmFieldNumber;
const int LocalAlgorithms::kFrequencyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LocalAlgorithms::LocalAlgorithms()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_local_planner.LocalAlgorithms)
}

void LocalAlgorithms::InitAsDefaultInstance() {
}

LocalAlgorithms::LocalAlgorithms(const LocalAlgorithms& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_local_planner.LocalAlgorithms)
}

void LocalAlgorithms::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frequency_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LocalAlgorithms::~LocalAlgorithms() {
  // @@protoc_insertion_point(destructor:roborts_local_planner.LocalAlgorithms)
  SharedDtor();
}

void LocalAlgorithms::SharedDtor() {
  selected_algorithm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void LocalAlgorithms::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LocalAlgorithms::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LocalAlgorithms_descriptor_;
}

const LocalAlgorithms& LocalAlgorithms::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_local_5fplanner_2eproto();
  return *default_instance_;
}

LocalAlgorithms* LocalAlgorithms::default_instance_ = NULL;

LocalAlgorithms* LocalAlgorithms::New(::google::protobuf::Arena* arena) const {
  LocalAlgorithms* n = new LocalAlgorithms;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LocalAlgorithms::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_local_planner.LocalAlgorithms)
  if (_has_bits_[0 / 32] & 6u) {
    if (has_selected_algorithm()) {
      selected_algorithm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    frequency_ = 0;
  }
  name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool LocalAlgorithms::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_local_planner.LocalAlgorithms)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (tag == 10) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_local_planner.LocalAlgorithms.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(18)) goto parse_selected_algorithm;
        break;
      }

      // optional string selected_algorithm = 2;
      case 2: {
        if (tag == 18) {
         parse_selected_algorithm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selected_algorithm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selected_algorithm().data(), this->selected_algorithm().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_local_planner.LocalAlgorithms.selected_algorithm");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_frequency;
        break;
      }

      // optional double frequency = 3;
      case 3: {
        if (tag == 25) {
         parse_frequency:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &frequency_)));
          set_has_frequency();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_local_planner.LocalAlgorithms)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_local_planner.LocalAlgorithms)
  return false;
#undef DO_
}

void LocalAlgorithms::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_local_planner.LocalAlgorithms)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.selected_algorithm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->selected_algorithm(), output);
  }

  // optional double frequency = 3;
  if (has_frequency()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->frequency(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_local_planner.LocalAlgorithms)
}

::google::protobuf::uint8* LocalAlgorithms::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_local_planner.LocalAlgorithms)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_local_planner.LocalAlgorithms.selected_algorithm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->selected_algorithm(), target);
  }

  // optional double frequency = 3;
  if (has_frequency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->frequency(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_local_planner.LocalAlgorithms)
  return target;
}

int LocalAlgorithms::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_local_planner.LocalAlgorithms)
  int total_size = 0;

  if (_has_bits_[1 / 32] & 6u) {
    // optional string selected_algorithm = 2;
    if (has_selected_algorithm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selected_algorithm());
    }

    // optional double frequency = 3;
    if (has_frequency()) {
      total_size += 1 + 8;
    }

  }
  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LocalAlgorithms::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_local_planner.LocalAlgorithms)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LocalAlgorithms* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LocalAlgorithms>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_local_planner.LocalAlgorithms)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_local_planner.LocalAlgorithms)
    MergeFrom(*source);
  }
}

void LocalAlgorithms::MergeFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_local_planner.LocalAlgorithms)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  name_.MergeFrom(from.name_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_selected_algorithm()) {
      set_has_selected_algorithm();
      selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
    }
    if (from.has_frequency()) {
      set_frequency(from.frequency());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void LocalAlgorithms::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocalAlgorithms::CopyFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalAlgorithms::IsInitialized() const {

  return true;
}

void LocalAlgorithms::Swap(LocalAlgorithms* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LocalAlgorithms::InternalSwap(LocalAlgorithms* other) {
  name_.UnsafeArenaSwap(&other->name_);
  selected_algorithm_.Swap(&other->selected_algorithm_);
  std::swap(frequency_, other->frequency_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LocalAlgorithms::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LocalAlgorithms_descriptor_;
  metadata.reflection = LocalAlgorithms_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LocalAlgorithms

// repeated string name = 1;
int LocalAlgorithms::name_size() const {
  return name_.size();
}
void LocalAlgorithms::clear_name() {
  name_.Clear();
}
 const ::std::string& LocalAlgorithms::name(int index) const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.name)
  return name_.Get(index);
}
 ::std::string* LocalAlgorithms::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_local_planner.LocalAlgorithms.name)
  return name_.Mutable(index);
}
 void LocalAlgorithms::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.name)
  name_.Mutable(index)->assign(value);
}
 void LocalAlgorithms::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:roborts_local_planner.LocalAlgorithms.name)
}
 void LocalAlgorithms::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roborts_local_planner.LocalAlgorithms.name)
}
 ::std::string* LocalAlgorithms::add_name() {
  // @@protoc_insertion_point(field_add_mutable:roborts_local_planner.LocalAlgorithms.name)
  return name_.Add();
}
 void LocalAlgorithms::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:roborts_local_planner.LocalAlgorithms.name)
}
 void LocalAlgorithms::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:roborts_local_planner.LocalAlgorithms.name)
}
 void LocalAlgorithms::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:roborts_local_planner.LocalAlgorithms.name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
LocalAlgorithms::name() const {
  // @@protoc_insertion_point(field_list:roborts_local_planner.LocalAlgorithms.name)
  return name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
LocalAlgorithms::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:roborts_local_planner.LocalAlgorithms.name)
  return &name_;
}

// optional string selected_algorithm = 2;
bool LocalAlgorithms::has_selected_algorithm() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void LocalAlgorithms::set_has_selected_algorithm() {
  _has_bits_[0] |= 0x00000002u;
}
void LocalAlgorithms::clear_has_selected_algorithm() {
  _has_bits_[0] &= ~0x00000002u;
}
void LocalAlgorithms::clear_selected_algorithm() {
  selected_algorithm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_selected_algorithm();
}
 const ::std::string& LocalAlgorithms::selected_algorithm() const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  return selected_algorithm_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LocalAlgorithms::set_selected_algorithm(const ::std::string& value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}
 void LocalAlgorithms::set_selected_algorithm(const char* value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}
 void LocalAlgorithms::set_selected_algorithm(const char* value, size_t size) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}
 ::std::string* LocalAlgorithms::mutable_selected_algorithm() {
  set_has_selected_algorithm();
  // @@protoc_insertion_point(field_mutable:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  return selected_algorithm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LocalAlgorithms::release_selected_algorithm() {
  // @@protoc_insertion_point(field_release:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  clear_has_selected_algorithm();
  return selected_algorithm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LocalAlgorithms::set_allocated_selected_algorithm(::std::string* selected_algorithm) {
  if (selected_algorithm != NULL) {
    set_has_selected_algorithm();
  } else {
    clear_has_selected_algorithm();
  }
  selected_algorithm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), selected_algorithm);
  // @@protoc_insertion_point(field_set_allocated:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}

// optional double frequency = 3;
bool LocalAlgorithms::has_frequency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void LocalAlgorithms::set_has_frequency() {
  _has_bits_[0] |= 0x00000004u;
}
void LocalAlgorithms::clear_has_frequency() {
  _has_bits_[0] &= ~0x00000004u;
}
void LocalAlgorithms::clear_frequency() {
  frequency_ = 0;
  clear_has_frequency();
}
 double LocalAlgorithms::frequency() const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.frequency)
  return frequency_;
}
 void LocalAlgorithms::set_frequency(double value) {
  set_has_frequency();
  frequency_ = value;
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.frequency)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_local_planner

// @@protoc_insertion_point(global_scope)
