// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armor_detection.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "armor_detection.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace roborts_detection {

namespace {

const ::google::protobuf::Descriptor* CameraGimbalTransform_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CameraGimbalTransform_reflection_ = NULL;
const ::google::protobuf::Descriptor* ProjectileModelInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProjectileModelInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* ArmorDetectionAlgorithms_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ArmorDetectionAlgorithms_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_armor_5fdetection_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_armor_5fdetection_2eproto() {
  protobuf_AddDesc_armor_5fdetection_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "armor_detection.proto");
  GOOGLE_CHECK(file != NULL);
  CameraGimbalTransform_descriptor_ = file->message_type(0);
  static const int CameraGimbalTransform_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, offset_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, offset_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, offset_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, offset_pitch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, offset_yaw_),
  };
  CameraGimbalTransform_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CameraGimbalTransform_descriptor_,
      CameraGimbalTransform::default_instance_,
      CameraGimbalTransform_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, _has_bits_[0]),
      -1,
      -1,
      sizeof(CameraGimbalTransform),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraGimbalTransform, _internal_metadata_),
      -1);
  ProjectileModelInfo_descriptor_ = file->message_type(1);
  static const int ProjectileModelInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProjectileModelInfo, init_v_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProjectileModelInfo, init_k_),
  };
  ProjectileModelInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ProjectileModelInfo_descriptor_,
      ProjectileModelInfo::default_instance_,
      ProjectileModelInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProjectileModelInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(ProjectileModelInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProjectileModelInfo, _internal_metadata_),
      -1);
  ArmorDetectionAlgorithms_descriptor_ = file->message_type(2);
  static const int ArmorDetectionAlgorithms_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, selected_algorithm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, undetected_armor_delay_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, camera_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, camera_gimbal_transform_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, projectile_model_info_),
  };
  ArmorDetectionAlgorithms_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ArmorDetectionAlgorithms_descriptor_,
      ArmorDetectionAlgorithms::default_instance_,
      ArmorDetectionAlgorithms_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, _has_bits_[0]),
      -1,
      -1,
      sizeof(ArmorDetectionAlgorithms),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ArmorDetectionAlgorithms, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_armor_5fdetection_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CameraGimbalTransform_descriptor_, &CameraGimbalTransform::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ProjectileModelInfo_descriptor_, &ProjectileModelInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ArmorDetectionAlgorithms_descriptor_, &ArmorDetectionAlgorithms::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_armor_5fdetection_2eproto() {
  delete CameraGimbalTransform::default_instance_;
  delete CameraGimbalTransform_reflection_;
  delete ProjectileModelInfo::default_instance_;
  delete ProjectileModelInfo_reflection_;
  delete ArmorDetectionAlgorithms::default_instance_;
  delete ArmorDetectionAlgorithms_reflection_;
}

void protobuf_AddDesc_armor_5fdetection_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_armor_5fdetection_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025armor_detection.proto\022\021roborts_detecti"
    "on\"w\n\025CameraGimbalTransform\022\020\n\010offset_x\030"
    "\001 \002(\002\022\020\n\010offset_y\030\002 \002(\002\022\020\n\010offset_z\030\003 \002("
    "\002\022\024\n\014offset_pitch\030\004 \002(\002\022\022\n\noffset_yaw\030\005 "
    "\002(\002\"5\n\023ProjectileModelInfo\022\016\n\006init_v\030\001 \001"
    "(\002\022\016\n\006init_k\030\002 \001(\002\"\213\002\n\030ArmorDetectionAlg"
    "orithms\022\014\n\004name\030\001 \003(\t\022\032\n\022selected_algori"
    "thm\030\002 \001(\t\022\036\n\026undetected_armor_delay\030\003 \001("
    "\r\022\023\n\013camera_name\030\004 \001(\t\022I\n\027camera_gimbal_"
    "transform\030\005 \002(\0132(.roborts_detection.Came"
    "raGimbalTransform\022E\n\025projectile_model_in"
    "fo\030\006 \001(\0132&.roborts_detection.ProjectileM"
    "odelInfo", 488);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "armor_detection.proto", &protobuf_RegisterTypes);
  CameraGimbalTransform::default_instance_ = new CameraGimbalTransform();
  ProjectileModelInfo::default_instance_ = new ProjectileModelInfo();
  ArmorDetectionAlgorithms::default_instance_ = new ArmorDetectionAlgorithms();
  CameraGimbalTransform::default_instance_->InitAsDefaultInstance();
  ProjectileModelInfo::default_instance_->InitAsDefaultInstance();
  ArmorDetectionAlgorithms::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_armor_5fdetection_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_armor_5fdetection_2eproto {
  StaticDescriptorInitializer_armor_5fdetection_2eproto() {
    protobuf_AddDesc_armor_5fdetection_2eproto();
  }
} static_descriptor_initializer_armor_5fdetection_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraGimbalTransform::kOffsetXFieldNumber;
const int CameraGimbalTransform::kOffsetYFieldNumber;
const int CameraGimbalTransform::kOffsetZFieldNumber;
const int CameraGimbalTransform::kOffsetPitchFieldNumber;
const int CameraGimbalTransform::kOffsetYawFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraGimbalTransform::CameraGimbalTransform()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_detection.CameraGimbalTransform)
}

void CameraGimbalTransform::InitAsDefaultInstance() {
}

CameraGimbalTransform::CameraGimbalTransform(const CameraGimbalTransform& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_detection.CameraGimbalTransform)
}

void CameraGimbalTransform::SharedCtor() {
  _cached_size_ = 0;
  offset_x_ = 0;
  offset_y_ = 0;
  offset_z_ = 0;
  offset_pitch_ = 0;
  offset_yaw_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CameraGimbalTransform::~CameraGimbalTransform() {
  // @@protoc_insertion_point(destructor:roborts_detection.CameraGimbalTransform)
  SharedDtor();
}

void CameraGimbalTransform::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CameraGimbalTransform::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraGimbalTransform::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CameraGimbalTransform_descriptor_;
}

const CameraGimbalTransform& CameraGimbalTransform::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_armor_5fdetection_2eproto();
  return *default_instance_;
}

CameraGimbalTransform* CameraGimbalTransform::default_instance_ = NULL;

CameraGimbalTransform* CameraGimbalTransform::New(::google::protobuf::Arena* arena) const {
  CameraGimbalTransform* n = new CameraGimbalTransform;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraGimbalTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_detection.CameraGimbalTransform)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(CameraGimbalTransform, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CameraGimbalTransform*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 31u) {
    ZR_(offset_x_, offset_yaw_);
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CameraGimbalTransform::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_detection.CameraGimbalTransform)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float offset_x = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_x_)));
          set_has_offset_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_offset_y;
        break;
      }

      // required float offset_y = 2;
      case 2: {
        if (tag == 21) {
         parse_offset_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_y_)));
          set_has_offset_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_offset_z;
        break;
      }

      // required float offset_z = 3;
      case 3: {
        if (tag == 29) {
         parse_offset_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_z_)));
          set_has_offset_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_offset_pitch;
        break;
      }

      // required float offset_pitch = 4;
      case 4: {
        if (tag == 37) {
         parse_offset_pitch:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_pitch_)));
          set_has_offset_pitch();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_offset_yaw;
        break;
      }

      // required float offset_yaw = 5;
      case 5: {
        if (tag == 45) {
         parse_offset_yaw:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_yaw_)));
          set_has_offset_yaw();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_detection.CameraGimbalTransform)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_detection.CameraGimbalTransform)
  return false;
#undef DO_
}

void CameraGimbalTransform::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_detection.CameraGimbalTransform)
  // required float offset_x = 1;
  if (has_offset_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->offset_x(), output);
  }

  // required float offset_y = 2;
  if (has_offset_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->offset_y(), output);
  }

  // required float offset_z = 3;
  if (has_offset_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->offset_z(), output);
  }

  // required float offset_pitch = 4;
  if (has_offset_pitch()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->offset_pitch(), output);
  }

  // required float offset_yaw = 5;
  if (has_offset_yaw()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->offset_yaw(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_detection.CameraGimbalTransform)
}

::google::protobuf::uint8* CameraGimbalTransform::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_detection.CameraGimbalTransform)
  // required float offset_x = 1;
  if (has_offset_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->offset_x(), target);
  }

  // required float offset_y = 2;
  if (has_offset_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->offset_y(), target);
  }

  // required float offset_z = 3;
  if (has_offset_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->offset_z(), target);
  }

  // required float offset_pitch = 4;
  if (has_offset_pitch()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->offset_pitch(), target);
  }

  // required float offset_yaw = 5;
  if (has_offset_yaw()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->offset_yaw(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_detection.CameraGimbalTransform)
  return target;
}

int CameraGimbalTransform::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:roborts_detection.CameraGimbalTransform)
  int total_size = 0;

  if (has_offset_x()) {
    // required float offset_x = 1;
    total_size += 1 + 4;
  }

  if (has_offset_y()) {
    // required float offset_y = 2;
    total_size += 1 + 4;
  }

  if (has_offset_z()) {
    // required float offset_z = 3;
    total_size += 1 + 4;
  }

  if (has_offset_pitch()) {
    // required float offset_pitch = 4;
    total_size += 1 + 4;
  }

  if (has_offset_yaw()) {
    // required float offset_yaw = 5;
    total_size += 1 + 4;
  }

  return total_size;
}
int CameraGimbalTransform::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_detection.CameraGimbalTransform)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required float offset_x = 1;
    total_size += 1 + 4;

    // required float offset_y = 2;
    total_size += 1 + 4;

    // required float offset_z = 3;
    total_size += 1 + 4;

    // required float offset_pitch = 4;
    total_size += 1 + 4;

    // required float offset_yaw = 5;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraGimbalTransform::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_detection.CameraGimbalTransform)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CameraGimbalTransform* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraGimbalTransform>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_detection.CameraGimbalTransform)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_detection.CameraGimbalTransform)
    MergeFrom(*source);
  }
}

void CameraGimbalTransform::MergeFrom(const CameraGimbalTransform& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_detection.CameraGimbalTransform)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_offset_x()) {
      set_offset_x(from.offset_x());
    }
    if (from.has_offset_y()) {
      set_offset_y(from.offset_y());
    }
    if (from.has_offset_z()) {
      set_offset_z(from.offset_z());
    }
    if (from.has_offset_pitch()) {
      set_offset_pitch(from.offset_pitch());
    }
    if (from.has_offset_yaw()) {
      set_offset_yaw(from.offset_yaw());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CameraGimbalTransform::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_detection.CameraGimbalTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraGimbalTransform::CopyFrom(const CameraGimbalTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_detection.CameraGimbalTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraGimbalTransform::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void CameraGimbalTransform::Swap(CameraGimbalTransform* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraGimbalTransform::InternalSwap(CameraGimbalTransform* other) {
  std::swap(offset_x_, other->offset_x_);
  std::swap(offset_y_, other->offset_y_);
  std::swap(offset_z_, other->offset_z_);
  std::swap(offset_pitch_, other->offset_pitch_);
  std::swap(offset_yaw_, other->offset_yaw_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraGimbalTransform::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CameraGimbalTransform_descriptor_;
  metadata.reflection = CameraGimbalTransform_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraGimbalTransform

// required float offset_x = 1;
bool CameraGimbalTransform::has_offset_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CameraGimbalTransform::set_has_offset_x() {
  _has_bits_[0] |= 0x00000001u;
}
void CameraGimbalTransform::clear_has_offset_x() {
  _has_bits_[0] &= ~0x00000001u;
}
void CameraGimbalTransform::clear_offset_x() {
  offset_x_ = 0;
  clear_has_offset_x();
}
 float CameraGimbalTransform::offset_x() const {
  // @@protoc_insertion_point(field_get:roborts_detection.CameraGimbalTransform.offset_x)
  return offset_x_;
}
 void CameraGimbalTransform::set_offset_x(float value) {
  set_has_offset_x();
  offset_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.CameraGimbalTransform.offset_x)
}

// required float offset_y = 2;
bool CameraGimbalTransform::has_offset_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CameraGimbalTransform::set_has_offset_y() {
  _has_bits_[0] |= 0x00000002u;
}
void CameraGimbalTransform::clear_has_offset_y() {
  _has_bits_[0] &= ~0x00000002u;
}
void CameraGimbalTransform::clear_offset_y() {
  offset_y_ = 0;
  clear_has_offset_y();
}
 float CameraGimbalTransform::offset_y() const {
  // @@protoc_insertion_point(field_get:roborts_detection.CameraGimbalTransform.offset_y)
  return offset_y_;
}
 void CameraGimbalTransform::set_offset_y(float value) {
  set_has_offset_y();
  offset_y_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.CameraGimbalTransform.offset_y)
}

// required float offset_z = 3;
bool CameraGimbalTransform::has_offset_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CameraGimbalTransform::set_has_offset_z() {
  _has_bits_[0] |= 0x00000004u;
}
void CameraGimbalTransform::clear_has_offset_z() {
  _has_bits_[0] &= ~0x00000004u;
}
void CameraGimbalTransform::clear_offset_z() {
  offset_z_ = 0;
  clear_has_offset_z();
}
 float CameraGimbalTransform::offset_z() const {
  // @@protoc_insertion_point(field_get:roborts_detection.CameraGimbalTransform.offset_z)
  return offset_z_;
}
 void CameraGimbalTransform::set_offset_z(float value) {
  set_has_offset_z();
  offset_z_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.CameraGimbalTransform.offset_z)
}

// required float offset_pitch = 4;
bool CameraGimbalTransform::has_offset_pitch() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void CameraGimbalTransform::set_has_offset_pitch() {
  _has_bits_[0] |= 0x00000008u;
}
void CameraGimbalTransform::clear_has_offset_pitch() {
  _has_bits_[0] &= ~0x00000008u;
}
void CameraGimbalTransform::clear_offset_pitch() {
  offset_pitch_ = 0;
  clear_has_offset_pitch();
}
 float CameraGimbalTransform::offset_pitch() const {
  // @@protoc_insertion_point(field_get:roborts_detection.CameraGimbalTransform.offset_pitch)
  return offset_pitch_;
}
 void CameraGimbalTransform::set_offset_pitch(float value) {
  set_has_offset_pitch();
  offset_pitch_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.CameraGimbalTransform.offset_pitch)
}

// required float offset_yaw = 5;
bool CameraGimbalTransform::has_offset_yaw() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void CameraGimbalTransform::set_has_offset_yaw() {
  _has_bits_[0] |= 0x00000010u;
}
void CameraGimbalTransform::clear_has_offset_yaw() {
  _has_bits_[0] &= ~0x00000010u;
}
void CameraGimbalTransform::clear_offset_yaw() {
  offset_yaw_ = 0;
  clear_has_offset_yaw();
}
 float CameraGimbalTransform::offset_yaw() const {
  // @@protoc_insertion_point(field_get:roborts_detection.CameraGimbalTransform.offset_yaw)
  return offset_yaw_;
}
 void CameraGimbalTransform::set_offset_yaw(float value) {
  set_has_offset_yaw();
  offset_yaw_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.CameraGimbalTransform.offset_yaw)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProjectileModelInfo::kInitVFieldNumber;
const int ProjectileModelInfo::kInitKFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProjectileModelInfo::ProjectileModelInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_detection.ProjectileModelInfo)
}

void ProjectileModelInfo::InitAsDefaultInstance() {
}

ProjectileModelInfo::ProjectileModelInfo(const ProjectileModelInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_detection.ProjectileModelInfo)
}

void ProjectileModelInfo::SharedCtor() {
  _cached_size_ = 0;
  init_v_ = 0;
  init_k_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProjectileModelInfo::~ProjectileModelInfo() {
  // @@protoc_insertion_point(destructor:roborts_detection.ProjectileModelInfo)
  SharedDtor();
}

void ProjectileModelInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ProjectileModelInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProjectileModelInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProjectileModelInfo_descriptor_;
}

const ProjectileModelInfo& ProjectileModelInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_armor_5fdetection_2eproto();
  return *default_instance_;
}

ProjectileModelInfo* ProjectileModelInfo::default_instance_ = NULL;

ProjectileModelInfo* ProjectileModelInfo::New(::google::protobuf::Arena* arena) const {
  ProjectileModelInfo* n = new ProjectileModelInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProjectileModelInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_detection.ProjectileModelInfo)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ProjectileModelInfo, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ProjectileModelInfo*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(init_v_, init_k_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ProjectileModelInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_detection.ProjectileModelInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float init_v = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &init_v_)));
          set_has_init_v();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_init_k;
        break;
      }

      // optional float init_k = 2;
      case 2: {
        if (tag == 21) {
         parse_init_k:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &init_k_)));
          set_has_init_k();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_detection.ProjectileModelInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_detection.ProjectileModelInfo)
  return false;
#undef DO_
}

void ProjectileModelInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_detection.ProjectileModelInfo)
  // optional float init_v = 1;
  if (has_init_v()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->init_v(), output);
  }

  // optional float init_k = 2;
  if (has_init_k()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->init_k(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_detection.ProjectileModelInfo)
}

::google::protobuf::uint8* ProjectileModelInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_detection.ProjectileModelInfo)
  // optional float init_v = 1;
  if (has_init_v()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->init_v(), target);
  }

  // optional float init_k = 2;
  if (has_init_k()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->init_k(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_detection.ProjectileModelInfo)
  return target;
}

int ProjectileModelInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_detection.ProjectileModelInfo)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3u) {
    // optional float init_v = 1;
    if (has_init_v()) {
      total_size += 1 + 4;
    }

    // optional float init_k = 2;
    if (has_init_k()) {
      total_size += 1 + 4;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProjectileModelInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_detection.ProjectileModelInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ProjectileModelInfo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ProjectileModelInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_detection.ProjectileModelInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_detection.ProjectileModelInfo)
    MergeFrom(*source);
  }
}

void ProjectileModelInfo::MergeFrom(const ProjectileModelInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_detection.ProjectileModelInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_init_v()) {
      set_init_v(from.init_v());
    }
    if (from.has_init_k()) {
      set_init_k(from.init_k());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ProjectileModelInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_detection.ProjectileModelInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProjectileModelInfo::CopyFrom(const ProjectileModelInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_detection.ProjectileModelInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProjectileModelInfo::IsInitialized() const {

  return true;
}

void ProjectileModelInfo::Swap(ProjectileModelInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProjectileModelInfo::InternalSwap(ProjectileModelInfo* other) {
  std::swap(init_v_, other->init_v_);
  std::swap(init_k_, other->init_k_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProjectileModelInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProjectileModelInfo_descriptor_;
  metadata.reflection = ProjectileModelInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ProjectileModelInfo

// optional float init_v = 1;
bool ProjectileModelInfo::has_init_v() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ProjectileModelInfo::set_has_init_v() {
  _has_bits_[0] |= 0x00000001u;
}
void ProjectileModelInfo::clear_has_init_v() {
  _has_bits_[0] &= ~0x00000001u;
}
void ProjectileModelInfo::clear_init_v() {
  init_v_ = 0;
  clear_has_init_v();
}
 float ProjectileModelInfo::init_v() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ProjectileModelInfo.init_v)
  return init_v_;
}
 void ProjectileModelInfo::set_init_v(float value) {
  set_has_init_v();
  init_v_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.ProjectileModelInfo.init_v)
}

// optional float init_k = 2;
bool ProjectileModelInfo::has_init_k() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ProjectileModelInfo::set_has_init_k() {
  _has_bits_[0] |= 0x00000002u;
}
void ProjectileModelInfo::clear_has_init_k() {
  _has_bits_[0] &= ~0x00000002u;
}
void ProjectileModelInfo::clear_init_k() {
  init_k_ = 0;
  clear_has_init_k();
}
 float ProjectileModelInfo::init_k() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ProjectileModelInfo.init_k)
  return init_k_;
}
 void ProjectileModelInfo::set_init_k(float value) {
  set_has_init_k();
  init_k_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.ProjectileModelInfo.init_k)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArmorDetectionAlgorithms::kNameFieldNumber;
const int ArmorDetectionAlgorithms::kSelectedAlgorithmFieldNumber;
const int ArmorDetectionAlgorithms::kUndetectedArmorDelayFieldNumber;
const int ArmorDetectionAlgorithms::kCameraNameFieldNumber;
const int ArmorDetectionAlgorithms::kCameraGimbalTransformFieldNumber;
const int ArmorDetectionAlgorithms::kProjectileModelInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArmorDetectionAlgorithms::ArmorDetectionAlgorithms()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_detection.ArmorDetectionAlgorithms)
}

void ArmorDetectionAlgorithms::InitAsDefaultInstance() {
  camera_gimbal_transform_ = const_cast< ::roborts_detection::CameraGimbalTransform*>(&::roborts_detection::CameraGimbalTransform::default_instance());
  projectile_model_info_ = const_cast< ::roborts_detection::ProjectileModelInfo*>(&::roborts_detection::ProjectileModelInfo::default_instance());
}

ArmorDetectionAlgorithms::ArmorDetectionAlgorithms(const ArmorDetectionAlgorithms& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_detection.ArmorDetectionAlgorithms)
}

void ArmorDetectionAlgorithms::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  undetected_armor_delay_ = 0u;
  camera_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_gimbal_transform_ = NULL;
  projectile_model_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ArmorDetectionAlgorithms::~ArmorDetectionAlgorithms() {
  // @@protoc_insertion_point(destructor:roborts_detection.ArmorDetectionAlgorithms)
  SharedDtor();
}

void ArmorDetectionAlgorithms::SharedDtor() {
  selected_algorithm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete camera_gimbal_transform_;
    delete projectile_model_info_;
  }
}

void ArmorDetectionAlgorithms::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ArmorDetectionAlgorithms::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ArmorDetectionAlgorithms_descriptor_;
}

const ArmorDetectionAlgorithms& ArmorDetectionAlgorithms::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_armor_5fdetection_2eproto();
  return *default_instance_;
}

ArmorDetectionAlgorithms* ArmorDetectionAlgorithms::default_instance_ = NULL;

ArmorDetectionAlgorithms* ArmorDetectionAlgorithms::New(::google::protobuf::Arena* arena) const {
  ArmorDetectionAlgorithms* n = new ArmorDetectionAlgorithms;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ArmorDetectionAlgorithms::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_detection.ArmorDetectionAlgorithms)
  if (_has_bits_[0 / 32] & 62u) {
    if (has_selected_algorithm()) {
      selected_algorithm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    undetected_armor_delay_ = 0u;
    if (has_camera_name()) {
      camera_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_camera_gimbal_transform()) {
      if (camera_gimbal_transform_ != NULL) camera_gimbal_transform_->::roborts_detection::CameraGimbalTransform::Clear();
    }
    if (has_projectile_model_info()) {
      if (projectile_model_info_ != NULL) projectile_model_info_->::roborts_detection::ProjectileModelInfo::Clear();
    }
  }
  name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ArmorDetectionAlgorithms::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_detection.ArmorDetectionAlgorithms)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (tag == 10) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_detection.ArmorDetectionAlgorithms.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(18)) goto parse_selected_algorithm;
        break;
      }

      // optional string selected_algorithm = 2;
      case 2: {
        if (tag == 18) {
         parse_selected_algorithm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selected_algorithm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selected_algorithm().data(), this->selected_algorithm().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_detection.ArmorDetectionAlgorithms.selected_algorithm");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_undetected_armor_delay;
        break;
      }

      // optional uint32 undetected_armor_delay = 3;
      case 3: {
        if (tag == 24) {
         parse_undetected_armor_delay:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &undetected_armor_delay_)));
          set_has_undetected_armor_delay();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_camera_name;
        break;
      }

      // optional string camera_name = 4;
      case 4: {
        if (tag == 34) {
         parse_camera_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camera_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->camera_name().data(), this->camera_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_detection.ArmorDetectionAlgorithms.camera_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_camera_gimbal_transform;
        break;
      }

      // required .roborts_detection.CameraGimbalTransform camera_gimbal_transform = 5;
      case 5: {
        if (tag == 42) {
         parse_camera_gimbal_transform:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_camera_gimbal_transform()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_projectile_model_info;
        break;
      }

      // optional .roborts_detection.ProjectileModelInfo projectile_model_info = 6;
      case 6: {
        if (tag == 50) {
         parse_projectile_model_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_projectile_model_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_detection.ArmorDetectionAlgorithms)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_detection.ArmorDetectionAlgorithms)
  return false;
#undef DO_
}

void ArmorDetectionAlgorithms::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_detection.ArmorDetectionAlgorithms)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.selected_algorithm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->selected_algorithm(), output);
  }

  // optional uint32 undetected_armor_delay = 3;
  if (has_undetected_armor_delay()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->undetected_armor_delay(), output);
  }

  // optional string camera_name = 4;
  if (has_camera_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_name().data(), this->camera_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.camera_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->camera_name(), output);
  }

  // required .roborts_detection.CameraGimbalTransform camera_gimbal_transform = 5;
  if (has_camera_gimbal_transform()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->camera_gimbal_transform_, output);
  }

  // optional .roborts_detection.ProjectileModelInfo projectile_model_info = 6;
  if (has_projectile_model_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->projectile_model_info_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_detection.ArmorDetectionAlgorithms)
}

::google::protobuf::uint8* ArmorDetectionAlgorithms::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_detection.ArmorDetectionAlgorithms)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.selected_algorithm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->selected_algorithm(), target);
  }

  // optional uint32 undetected_armor_delay = 3;
  if (has_undetected_armor_delay()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->undetected_armor_delay(), target);
  }

  // optional string camera_name = 4;
  if (has_camera_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_name().data(), this->camera_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_detection.ArmorDetectionAlgorithms.camera_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->camera_name(), target);
  }

  // required .roborts_detection.CameraGimbalTransform camera_gimbal_transform = 5;
  if (has_camera_gimbal_transform()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->camera_gimbal_transform_, false, target);
  }

  // optional .roborts_detection.ProjectileModelInfo projectile_model_info = 6;
  if (has_projectile_model_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->projectile_model_info_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_detection.ArmorDetectionAlgorithms)
  return target;
}

int ArmorDetectionAlgorithms::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_detection.ArmorDetectionAlgorithms)
  int total_size = 0;

  // required .roborts_detection.CameraGimbalTransform camera_gimbal_transform = 5;
  if (has_camera_gimbal_transform()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->camera_gimbal_transform_);
  }
  if (_has_bits_[1 / 32] & 46u) {
    // optional string selected_algorithm = 2;
    if (has_selected_algorithm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selected_algorithm());
    }

    // optional uint32 undetected_armor_delay = 3;
    if (has_undetected_armor_delay()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->undetected_armor_delay());
    }

    // optional string camera_name = 4;
    if (has_camera_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->camera_name());
    }

    // optional .roborts_detection.ProjectileModelInfo projectile_model_info = 6;
    if (has_projectile_model_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->projectile_model_info_);
    }

  }
  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ArmorDetectionAlgorithms::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_detection.ArmorDetectionAlgorithms)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ArmorDetectionAlgorithms* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ArmorDetectionAlgorithms>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_detection.ArmorDetectionAlgorithms)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_detection.ArmorDetectionAlgorithms)
    MergeFrom(*source);
  }
}

void ArmorDetectionAlgorithms::MergeFrom(const ArmorDetectionAlgorithms& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_detection.ArmorDetectionAlgorithms)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  name_.MergeFrom(from.name_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_selected_algorithm()) {
      set_has_selected_algorithm();
      selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
    }
    if (from.has_undetected_armor_delay()) {
      set_undetected_armor_delay(from.undetected_armor_delay());
    }
    if (from.has_camera_name()) {
      set_has_camera_name();
      camera_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camera_name_);
    }
    if (from.has_camera_gimbal_transform()) {
      mutable_camera_gimbal_transform()->::roborts_detection::CameraGimbalTransform::MergeFrom(from.camera_gimbal_transform());
    }
    if (from.has_projectile_model_info()) {
      mutable_projectile_model_info()->::roborts_detection::ProjectileModelInfo::MergeFrom(from.projectile_model_info());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ArmorDetectionAlgorithms::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_detection.ArmorDetectionAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArmorDetectionAlgorithms::CopyFrom(const ArmorDetectionAlgorithms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_detection.ArmorDetectionAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmorDetectionAlgorithms::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000010) != 0x00000010) return false;

  if (has_camera_gimbal_transform()) {
    if (!this->camera_gimbal_transform_->IsInitialized()) return false;
  }
  return true;
}

void ArmorDetectionAlgorithms::Swap(ArmorDetectionAlgorithms* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArmorDetectionAlgorithms::InternalSwap(ArmorDetectionAlgorithms* other) {
  name_.UnsafeArenaSwap(&other->name_);
  selected_algorithm_.Swap(&other->selected_algorithm_);
  std::swap(undetected_armor_delay_, other->undetected_armor_delay_);
  camera_name_.Swap(&other->camera_name_);
  std::swap(camera_gimbal_transform_, other->camera_gimbal_transform_);
  std::swap(projectile_model_info_, other->projectile_model_info_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ArmorDetectionAlgorithms::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ArmorDetectionAlgorithms_descriptor_;
  metadata.reflection = ArmorDetectionAlgorithms_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ArmorDetectionAlgorithms

// repeated string name = 1;
int ArmorDetectionAlgorithms::name_size() const {
  return name_.size();
}
void ArmorDetectionAlgorithms::clear_name() {
  name_.Clear();
}
 const ::std::string& ArmorDetectionAlgorithms::name(int index) const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.name)
  return name_.Get(index);
}
 ::std::string* ArmorDetectionAlgorithms::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_detection.ArmorDetectionAlgorithms.name)
  return name_.Mutable(index);
}
 void ArmorDetectionAlgorithms::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:roborts_detection.ArmorDetectionAlgorithms.name)
  name_.Mutable(index)->assign(value);
}
 void ArmorDetectionAlgorithms::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:roborts_detection.ArmorDetectionAlgorithms.name)
}
 void ArmorDetectionAlgorithms::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roborts_detection.ArmorDetectionAlgorithms.name)
}
 ::std::string* ArmorDetectionAlgorithms::add_name() {
  // @@protoc_insertion_point(field_add_mutable:roborts_detection.ArmorDetectionAlgorithms.name)
  return name_.Add();
}
 void ArmorDetectionAlgorithms::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:roborts_detection.ArmorDetectionAlgorithms.name)
}
 void ArmorDetectionAlgorithms::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:roborts_detection.ArmorDetectionAlgorithms.name)
}
 void ArmorDetectionAlgorithms::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:roborts_detection.ArmorDetectionAlgorithms.name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
ArmorDetectionAlgorithms::name() const {
  // @@protoc_insertion_point(field_list:roborts_detection.ArmorDetectionAlgorithms.name)
  return name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
ArmorDetectionAlgorithms::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:roborts_detection.ArmorDetectionAlgorithms.name)
  return &name_;
}

// optional string selected_algorithm = 2;
bool ArmorDetectionAlgorithms::has_selected_algorithm() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ArmorDetectionAlgorithms::set_has_selected_algorithm() {
  _has_bits_[0] |= 0x00000002u;
}
void ArmorDetectionAlgorithms::clear_has_selected_algorithm() {
  _has_bits_[0] &= ~0x00000002u;
}
void ArmorDetectionAlgorithms::clear_selected_algorithm() {
  selected_algorithm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_selected_algorithm();
}
 const ::std::string& ArmorDetectionAlgorithms::selected_algorithm() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
  return selected_algorithm_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ArmorDetectionAlgorithms::set_selected_algorithm(const ::std::string& value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
}
 void ArmorDetectionAlgorithms::set_selected_algorithm(const char* value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
}
 void ArmorDetectionAlgorithms::set_selected_algorithm(const char* value, size_t size) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
}
 ::std::string* ArmorDetectionAlgorithms::mutable_selected_algorithm() {
  set_has_selected_algorithm();
  // @@protoc_insertion_point(field_mutable:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
  return selected_algorithm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ArmorDetectionAlgorithms::release_selected_algorithm() {
  // @@protoc_insertion_point(field_release:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
  clear_has_selected_algorithm();
  return selected_algorithm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ArmorDetectionAlgorithms::set_allocated_selected_algorithm(::std::string* selected_algorithm) {
  if (selected_algorithm != NULL) {
    set_has_selected_algorithm();
  } else {
    clear_has_selected_algorithm();
  }
  selected_algorithm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), selected_algorithm);
  // @@protoc_insertion_point(field_set_allocated:roborts_detection.ArmorDetectionAlgorithms.selected_algorithm)
}

// optional uint32 undetected_armor_delay = 3;
bool ArmorDetectionAlgorithms::has_undetected_armor_delay() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ArmorDetectionAlgorithms::set_has_undetected_armor_delay() {
  _has_bits_[0] |= 0x00000004u;
}
void ArmorDetectionAlgorithms::clear_has_undetected_armor_delay() {
  _has_bits_[0] &= ~0x00000004u;
}
void ArmorDetectionAlgorithms::clear_undetected_armor_delay() {
  undetected_armor_delay_ = 0u;
  clear_has_undetected_armor_delay();
}
 ::google::protobuf::uint32 ArmorDetectionAlgorithms::undetected_armor_delay() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.undetected_armor_delay)
  return undetected_armor_delay_;
}
 void ArmorDetectionAlgorithms::set_undetected_armor_delay(::google::protobuf::uint32 value) {
  set_has_undetected_armor_delay();
  undetected_armor_delay_ = value;
  // @@protoc_insertion_point(field_set:roborts_detection.ArmorDetectionAlgorithms.undetected_armor_delay)
}

// optional string camera_name = 4;
bool ArmorDetectionAlgorithms::has_camera_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ArmorDetectionAlgorithms::set_has_camera_name() {
  _has_bits_[0] |= 0x00000008u;
}
void ArmorDetectionAlgorithms::clear_has_camera_name() {
  _has_bits_[0] &= ~0x00000008u;
}
void ArmorDetectionAlgorithms::clear_camera_name() {
  camera_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_name();
}
 const ::std::string& ArmorDetectionAlgorithms::camera_name() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.camera_name)
  return camera_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ArmorDetectionAlgorithms::set_camera_name(const ::std::string& value) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_detection.ArmorDetectionAlgorithms.camera_name)
}
 void ArmorDetectionAlgorithms::set_camera_name(const char* value) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_detection.ArmorDetectionAlgorithms.camera_name)
}
 void ArmorDetectionAlgorithms::set_camera_name(const char* value, size_t size) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_detection.ArmorDetectionAlgorithms.camera_name)
}
 ::std::string* ArmorDetectionAlgorithms::mutable_camera_name() {
  set_has_camera_name();
  // @@protoc_insertion_point(field_mutable:roborts_detection.ArmorDetectionAlgorithms.camera_name)
  return camera_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ArmorDetectionAlgorithms::release_camera_name() {
  // @@protoc_insertion_point(field_release:roborts_detection.ArmorDetectionAlgorithms.camera_name)
  clear_has_camera_name();
  return camera_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ArmorDetectionAlgorithms::set_allocated_camera_name(::std::string* camera_name) {
  if (camera_name != NULL) {
    set_has_camera_name();
  } else {
    clear_has_camera_name();
  }
  camera_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_name);
  // @@protoc_insertion_point(field_set_allocated:roborts_detection.ArmorDetectionAlgorithms.camera_name)
}

// required .roborts_detection.CameraGimbalTransform camera_gimbal_transform = 5;
bool ArmorDetectionAlgorithms::has_camera_gimbal_transform() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void ArmorDetectionAlgorithms::set_has_camera_gimbal_transform() {
  _has_bits_[0] |= 0x00000010u;
}
void ArmorDetectionAlgorithms::clear_has_camera_gimbal_transform() {
  _has_bits_[0] &= ~0x00000010u;
}
void ArmorDetectionAlgorithms::clear_camera_gimbal_transform() {
  if (camera_gimbal_transform_ != NULL) camera_gimbal_transform_->::roborts_detection::CameraGimbalTransform::Clear();
  clear_has_camera_gimbal_transform();
}
const ::roborts_detection::CameraGimbalTransform& ArmorDetectionAlgorithms::camera_gimbal_transform() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.camera_gimbal_transform)
  return camera_gimbal_transform_ != NULL ? *camera_gimbal_transform_ : *default_instance_->camera_gimbal_transform_;
}
::roborts_detection::CameraGimbalTransform* ArmorDetectionAlgorithms::mutable_camera_gimbal_transform() {
  set_has_camera_gimbal_transform();
  if (camera_gimbal_transform_ == NULL) {
    camera_gimbal_transform_ = new ::roborts_detection::CameraGimbalTransform;
  }
  // @@protoc_insertion_point(field_mutable:roborts_detection.ArmorDetectionAlgorithms.camera_gimbal_transform)
  return camera_gimbal_transform_;
}
::roborts_detection::CameraGimbalTransform* ArmorDetectionAlgorithms::release_camera_gimbal_transform() {
  // @@protoc_insertion_point(field_release:roborts_detection.ArmorDetectionAlgorithms.camera_gimbal_transform)
  clear_has_camera_gimbal_transform();
  ::roborts_detection::CameraGimbalTransform* temp = camera_gimbal_transform_;
  camera_gimbal_transform_ = NULL;
  return temp;
}
void ArmorDetectionAlgorithms::set_allocated_camera_gimbal_transform(::roborts_detection::CameraGimbalTransform* camera_gimbal_transform) {
  delete camera_gimbal_transform_;
  camera_gimbal_transform_ = camera_gimbal_transform;
  if (camera_gimbal_transform) {
    set_has_camera_gimbal_transform();
  } else {
    clear_has_camera_gimbal_transform();
  }
  // @@protoc_insertion_point(field_set_allocated:roborts_detection.ArmorDetectionAlgorithms.camera_gimbal_transform)
}

// optional .roborts_detection.ProjectileModelInfo projectile_model_info = 6;
bool ArmorDetectionAlgorithms::has_projectile_model_info() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void ArmorDetectionAlgorithms::set_has_projectile_model_info() {
  _has_bits_[0] |= 0x00000020u;
}
void ArmorDetectionAlgorithms::clear_has_projectile_model_info() {
  _has_bits_[0] &= ~0x00000020u;
}
void ArmorDetectionAlgorithms::clear_projectile_model_info() {
  if (projectile_model_info_ != NULL) projectile_model_info_->::roborts_detection::ProjectileModelInfo::Clear();
  clear_has_projectile_model_info();
}
const ::roborts_detection::ProjectileModelInfo& ArmorDetectionAlgorithms::projectile_model_info() const {
  // @@protoc_insertion_point(field_get:roborts_detection.ArmorDetectionAlgorithms.projectile_model_info)
  return projectile_model_info_ != NULL ? *projectile_model_info_ : *default_instance_->projectile_model_info_;
}
::roborts_detection::ProjectileModelInfo* ArmorDetectionAlgorithms::mutable_projectile_model_info() {
  set_has_projectile_model_info();
  if (projectile_model_info_ == NULL) {
    projectile_model_info_ = new ::roborts_detection::ProjectileModelInfo;
  }
  // @@protoc_insertion_point(field_mutable:roborts_detection.ArmorDetectionAlgorithms.projectile_model_info)
  return projectile_model_info_;
}
::roborts_detection::ProjectileModelInfo* ArmorDetectionAlgorithms::release_projectile_model_info() {
  // @@protoc_insertion_point(field_release:roborts_detection.ArmorDetectionAlgorithms.projectile_model_info)
  clear_has_projectile_model_info();
  ::roborts_detection::ProjectileModelInfo* temp = projectile_model_info_;
  projectile_model_info_ = NULL;
  return temp;
}
void ArmorDetectionAlgorithms::set_allocated_projectile_model_info(::roborts_detection::ProjectileModelInfo* projectile_model_info) {
  delete projectile_model_info_;
  projectile_model_info_ = projectile_model_info;
  if (projectile_model_info) {
    set_has_projectile_model_info();
  } else {
    clear_has_projectile_model_info();
  }
  // @@protoc_insertion_point(field_set_allocated:roborts_detection.ArmorDetectionAlgorithms.projectile_model_info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_detection

// @@protoc_insertion_point(global_scope)
