// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_param.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "camera_param.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace roborts_camera {

namespace {

const ::google::protobuf::Descriptor* CameraMatrix_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CameraMatrix_reflection_ = NULL;
const ::google::protobuf::Descriptor* CameraDistortion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CameraDistortion_reflection_ = NULL;
const ::google::protobuf::Descriptor* Resolution_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Resolution_reflection_ = NULL;
const ::google::protobuf::Descriptor* Camera_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Camera_reflection_ = NULL;
const ::google::protobuf::Descriptor* Cameras_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Cameras_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_camera_5fparam_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_camera_5fparam_2eproto() {
  protobuf_AddDesc_camera_5fparam_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "camera_param.proto");
  GOOGLE_CHECK(file != NULL);
  CameraMatrix_descriptor_ = file->message_type(0);
  static const int CameraMatrix_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraMatrix, data_),
  };
  CameraMatrix_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CameraMatrix_descriptor_,
      CameraMatrix::default_instance_,
      CameraMatrix_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraMatrix, _has_bits_[0]),
      -1,
      -1,
      sizeof(CameraMatrix),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraMatrix, _internal_metadata_),
      -1);
  CameraDistortion_descriptor_ = file->message_type(1);
  static const int CameraDistortion_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraDistortion, data_),
  };
  CameraDistortion_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CameraDistortion_descriptor_,
      CameraDistortion::default_instance_,
      CameraDistortion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraDistortion, _has_bits_[0]),
      -1,
      -1,
      sizeof(CameraDistortion),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraDistortion, _internal_metadata_),
      -1);
  Resolution_descriptor_ = file->message_type(2);
  static const int Resolution_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, width_offset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, height_offset_),
  };
  Resolution_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Resolution_descriptor_,
      Resolution::default_instance_,
      Resolution_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, _has_bits_[0]),
      -1,
      -1,
      sizeof(Resolution),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resolution, _internal_metadata_),
      -1);
  Camera_descriptor_ = file->message_type(3);
  static const int Camera_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camera_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camera_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camera_path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camera_matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, camera_distortion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, fps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, resolution_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, auto_exposure_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, exposure_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, exposure_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, auto_white_balance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, auto_gain_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, contrast_),
  };
  Camera_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Camera_descriptor_,
      Camera::default_instance_,
      Camera_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, _has_bits_[0]),
      -1,
      -1,
      sizeof(Camera),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Camera, _internal_metadata_),
      -1);
  Cameras_descriptor_ = file->message_type(4);
  static const int Cameras_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cameras, camera_),
  };
  Cameras_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Cameras_descriptor_,
      Cameras::default_instance_,
      Cameras_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cameras, _has_bits_[0]),
      -1,
      -1,
      sizeof(Cameras),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cameras, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_camera_5fparam_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CameraMatrix_descriptor_, &CameraMatrix::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CameraDistortion_descriptor_, &CameraDistortion::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Resolution_descriptor_, &Resolution::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Camera_descriptor_, &Camera::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Cameras_descriptor_, &Cameras::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_camera_5fparam_2eproto() {
  delete CameraMatrix::default_instance_;
  delete CameraMatrix_reflection_;
  delete CameraDistortion::default_instance_;
  delete CameraDistortion_reflection_;
  delete Resolution::default_instance_;
  delete Resolution_reflection_;
  delete Camera::default_instance_;
  delete Camera_reflection_;
  delete Cameras::default_instance_;
  delete Cameras_reflection_;
}

void protobuf_AddDesc_camera_5fparam_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_camera_5fparam_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022camera_param.proto\022\016roborts_camera\"\034\n\014"
    "CameraMatrix\022\014\n\004data\030\001 \003(\001\" \n\020CameraDist"
    "ortion\022\014\n\004data\030\001 \003(\001\"X\n\nResolution\022\r\n\005wi"
    "dth\030\001 \002(\r\022\016\n\006height\030\002 \002(\r\022\024\n\014width_offse"
    "t\030\003 \002(\r\022\025\n\rheight_offset\030\004 \002(\r\"\375\002\n\006Camer"
    "a\022\023\n\013camera_name\030\001 \002(\t\022\023\n\013camera_type\030\002 "
    "\002(\t\022\023\n\013camera_path\030\003 \002(\t\0223\n\rcamera_matri"
    "x\030\004 \002(\0132\034.roborts_camera.CameraMatrix\022;\n"
    "\021camera_distortion\030\005 \002(\0132 .roborts_camer"
    "a.CameraDistortion\022\013\n\003fps\030\006 \001(\r\022.\n\nresol"
    "ution\030\007 \001(\0132\032.roborts_camera.Resolution\022"
    "\025\n\rauto_exposure\030\010 \001(\010\022\026\n\016exposure_value"
    "\030\t \001(\r\022\025\n\rexposure_time\030\n \001(\r\022\032\n\022auto_wh"
    "ite_balance\030\013 \001(\010\022\021\n\tauto_gain\030\014 \001(\010\022\020\n\010"
    "contrast\030\r \001(\r\"1\n\007Cameras\022&\n\006camera\030\001 \003("
    "\0132\026.roborts_camera.Camera", 625);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "camera_param.proto", &protobuf_RegisterTypes);
  CameraMatrix::default_instance_ = new CameraMatrix();
  CameraDistortion::default_instance_ = new CameraDistortion();
  Resolution::default_instance_ = new Resolution();
  Camera::default_instance_ = new Camera();
  Cameras::default_instance_ = new Cameras();
  CameraMatrix::default_instance_->InitAsDefaultInstance();
  CameraDistortion::default_instance_->InitAsDefaultInstance();
  Resolution::default_instance_->InitAsDefaultInstance();
  Camera::default_instance_->InitAsDefaultInstance();
  Cameras::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_camera_5fparam_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_camera_5fparam_2eproto {
  StaticDescriptorInitializer_camera_5fparam_2eproto() {
    protobuf_AddDesc_camera_5fparam_2eproto();
  }
} static_descriptor_initializer_camera_5fparam_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraMatrix::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraMatrix::CameraMatrix()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_camera.CameraMatrix)
}

void CameraMatrix::InitAsDefaultInstance() {
}

CameraMatrix::CameraMatrix(const CameraMatrix& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_camera.CameraMatrix)
}

void CameraMatrix::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CameraMatrix::~CameraMatrix() {
  // @@protoc_insertion_point(destructor:roborts_camera.CameraMatrix)
  SharedDtor();
}

void CameraMatrix::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CameraMatrix::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraMatrix::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CameraMatrix_descriptor_;
}

const CameraMatrix& CameraMatrix::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fparam_2eproto();
  return *default_instance_;
}

CameraMatrix* CameraMatrix::default_instance_ = NULL;

CameraMatrix* CameraMatrix::New(::google::protobuf::Arena* arena) const {
  CameraMatrix* n = new CameraMatrix;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraMatrix::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_camera.CameraMatrix)
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CameraMatrix::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_camera.CameraMatrix)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated double data = 1;
      case 1: {
        if (tag == 9) {
         parse_data:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 9, input, this->mutable_data())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_data())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(9)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_camera.CameraMatrix)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_camera.CameraMatrix)
  return false;
#undef DO_
}

void CameraMatrix::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_camera.CameraMatrix)
  // repeated double data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      1, this->data(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_camera.CameraMatrix)
}

::google::protobuf::uint8* CameraMatrix::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_camera.CameraMatrix)
  // repeated double data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(1, this->data(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_camera.CameraMatrix)
  return target;
}

int CameraMatrix::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_camera.CameraMatrix)
  int total_size = 0;

  // repeated double data = 1;
  {
    int data_size = 0;
    data_size = 8 * this->data_size();
    total_size += 1 * this->data_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraMatrix::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_camera.CameraMatrix)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CameraMatrix* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraMatrix>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_camera.CameraMatrix)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_camera.CameraMatrix)
    MergeFrom(*source);
  }
}

void CameraMatrix::MergeFrom(const CameraMatrix& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_camera.CameraMatrix)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  data_.MergeFrom(from.data_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CameraMatrix::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_camera.CameraMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraMatrix::CopyFrom(const CameraMatrix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_camera.CameraMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraMatrix::IsInitialized() const {

  return true;
}

void CameraMatrix::Swap(CameraMatrix* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraMatrix::InternalSwap(CameraMatrix* other) {
  data_.UnsafeArenaSwap(&other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraMatrix::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CameraMatrix_descriptor_;
  metadata.reflection = CameraMatrix_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraMatrix

// repeated double data = 1;
int CameraMatrix::data_size() const {
  return data_.size();
}
void CameraMatrix::clear_data() {
  data_.Clear();
}
 double CameraMatrix::data(int index) const {
  // @@protoc_insertion_point(field_get:roborts_camera.CameraMatrix.data)
  return data_.Get(index);
}
 void CameraMatrix::set_data(int index, double value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:roborts_camera.CameraMatrix.data)
}
 void CameraMatrix::add_data(double value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:roborts_camera.CameraMatrix.data)
}
 const ::google::protobuf::RepeatedField< double >&
CameraMatrix::data() const {
  // @@protoc_insertion_point(field_list:roborts_camera.CameraMatrix.data)
  return data_;
}
 ::google::protobuf::RepeatedField< double >*
CameraMatrix::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:roborts_camera.CameraMatrix.data)
  return &data_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraDistortion::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraDistortion::CameraDistortion()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_camera.CameraDistortion)
}

void CameraDistortion::InitAsDefaultInstance() {
}

CameraDistortion::CameraDistortion(const CameraDistortion& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_camera.CameraDistortion)
}

void CameraDistortion::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CameraDistortion::~CameraDistortion() {
  // @@protoc_insertion_point(destructor:roborts_camera.CameraDistortion)
  SharedDtor();
}

void CameraDistortion::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CameraDistortion::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraDistortion::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CameraDistortion_descriptor_;
}

const CameraDistortion& CameraDistortion::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fparam_2eproto();
  return *default_instance_;
}

CameraDistortion* CameraDistortion::default_instance_ = NULL;

CameraDistortion* CameraDistortion::New(::google::protobuf::Arena* arena) const {
  CameraDistortion* n = new CameraDistortion;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraDistortion::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_camera.CameraDistortion)
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CameraDistortion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_camera.CameraDistortion)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated double data = 1;
      case 1: {
        if (tag == 9) {
         parse_data:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 9, input, this->mutable_data())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_data())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(9)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_camera.CameraDistortion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_camera.CameraDistortion)
  return false;
#undef DO_
}

void CameraDistortion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_camera.CameraDistortion)
  // repeated double data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      1, this->data(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_camera.CameraDistortion)
}

::google::protobuf::uint8* CameraDistortion::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_camera.CameraDistortion)
  // repeated double data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(1, this->data(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_camera.CameraDistortion)
  return target;
}

int CameraDistortion::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_camera.CameraDistortion)
  int total_size = 0;

  // repeated double data = 1;
  {
    int data_size = 0;
    data_size = 8 * this->data_size();
    total_size += 1 * this->data_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraDistortion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_camera.CameraDistortion)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CameraDistortion* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraDistortion>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_camera.CameraDistortion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_camera.CameraDistortion)
    MergeFrom(*source);
  }
}

void CameraDistortion::MergeFrom(const CameraDistortion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_camera.CameraDistortion)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  data_.MergeFrom(from.data_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CameraDistortion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_camera.CameraDistortion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraDistortion::CopyFrom(const CameraDistortion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_camera.CameraDistortion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraDistortion::IsInitialized() const {

  return true;
}

void CameraDistortion::Swap(CameraDistortion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraDistortion::InternalSwap(CameraDistortion* other) {
  data_.UnsafeArenaSwap(&other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraDistortion::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CameraDistortion_descriptor_;
  metadata.reflection = CameraDistortion_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraDistortion

// repeated double data = 1;
int CameraDistortion::data_size() const {
  return data_.size();
}
void CameraDistortion::clear_data() {
  data_.Clear();
}
 double CameraDistortion::data(int index) const {
  // @@protoc_insertion_point(field_get:roborts_camera.CameraDistortion.data)
  return data_.Get(index);
}
 void CameraDistortion::set_data(int index, double value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:roborts_camera.CameraDistortion.data)
}
 void CameraDistortion::add_data(double value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:roborts_camera.CameraDistortion.data)
}
 const ::google::protobuf::RepeatedField< double >&
CameraDistortion::data() const {
  // @@protoc_insertion_point(field_list:roborts_camera.CameraDistortion.data)
  return data_;
}
 ::google::protobuf::RepeatedField< double >*
CameraDistortion::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:roborts_camera.CameraDistortion.data)
  return &data_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Resolution::kWidthFieldNumber;
const int Resolution::kHeightFieldNumber;
const int Resolution::kWidthOffsetFieldNumber;
const int Resolution::kHeightOffsetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Resolution::Resolution()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_camera.Resolution)
}

void Resolution::InitAsDefaultInstance() {
}

Resolution::Resolution(const Resolution& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_camera.Resolution)
}

void Resolution::SharedCtor() {
  _cached_size_ = 0;
  width_ = 0u;
  height_ = 0u;
  width_offset_ = 0u;
  height_offset_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Resolution::~Resolution() {
  // @@protoc_insertion_point(destructor:roborts_camera.Resolution)
  SharedDtor();
}

void Resolution::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Resolution::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Resolution::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Resolution_descriptor_;
}

const Resolution& Resolution::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fparam_2eproto();
  return *default_instance_;
}

Resolution* Resolution::default_instance_ = NULL;

Resolution* Resolution::New(::google::protobuf::Arena* arena) const {
  Resolution* n = new Resolution;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Resolution::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_camera.Resolution)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Resolution, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Resolution*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(width_, height_offset_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Resolution::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_camera.Resolution)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 width = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_height;
        break;
      }

      // required uint32 height = 2;
      case 2: {
        if (tag == 16) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_width_offset;
        break;
      }

      // required uint32 width_offset = 3;
      case 3: {
        if (tag == 24) {
         parse_width_offset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_offset_)));
          set_has_width_offset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_height_offset;
        break;
      }

      // required uint32 height_offset = 4;
      case 4: {
        if (tag == 32) {
         parse_height_offset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_offset_)));
          set_has_height_offset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_camera.Resolution)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_camera.Resolution)
  return false;
#undef DO_
}

void Resolution::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_camera.Resolution)
  // required uint32 width = 1;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->width(), output);
  }

  // required uint32 height = 2;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->height(), output);
  }

  // required uint32 width_offset = 3;
  if (has_width_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->width_offset(), output);
  }

  // required uint32 height_offset = 4;
  if (has_height_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->height_offset(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_camera.Resolution)
}

::google::protobuf::uint8* Resolution::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_camera.Resolution)
  // required uint32 width = 1;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->width(), target);
  }

  // required uint32 height = 2;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->height(), target);
  }

  // required uint32 width_offset = 3;
  if (has_width_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->width_offset(), target);
  }

  // required uint32 height_offset = 4;
  if (has_height_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->height_offset(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_camera.Resolution)
  return target;
}

int Resolution::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:roborts_camera.Resolution)
  int total_size = 0;

  if (has_width()) {
    // required uint32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  if (has_height()) {
    // required uint32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  if (has_width_offset()) {
    // required uint32 width_offset = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width_offset());
  }

  if (has_height_offset()) {
    // required uint32 height_offset = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height_offset());
  }

  return total_size;
}
int Resolution::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_camera.Resolution)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint32 width = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());

    // required uint32 height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());

    // required uint32 width_offset = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width_offset());

    // required uint32 height_offset = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height_offset());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Resolution::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_camera.Resolution)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Resolution* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Resolution>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_camera.Resolution)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_camera.Resolution)
    MergeFrom(*source);
  }
}

void Resolution::MergeFrom(const Resolution& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_camera.Resolution)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
    if (from.has_width_offset()) {
      set_width_offset(from.width_offset());
    }
    if (from.has_height_offset()) {
      set_height_offset(from.height_offset());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Resolution::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_camera.Resolution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Resolution::CopyFrom(const Resolution& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_camera.Resolution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Resolution::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void Resolution::Swap(Resolution* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Resolution::InternalSwap(Resolution* other) {
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(width_offset_, other->width_offset_);
  std::swap(height_offset_, other->height_offset_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Resolution::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Resolution_descriptor_;
  metadata.reflection = Resolution_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Resolution

// required uint32 width = 1;
bool Resolution::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Resolution::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
void Resolution::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
void Resolution::clear_width() {
  width_ = 0u;
  clear_has_width();
}
 ::google::protobuf::uint32 Resolution::width() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Resolution.width)
  return width_;
}
 void Resolution::set_width(::google::protobuf::uint32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Resolution.width)
}

// required uint32 height = 2;
bool Resolution::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Resolution::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
void Resolution::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
void Resolution::clear_height() {
  height_ = 0u;
  clear_has_height();
}
 ::google::protobuf::uint32 Resolution::height() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Resolution.height)
  return height_;
}
 void Resolution::set_height(::google::protobuf::uint32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Resolution.height)
}

// required uint32 width_offset = 3;
bool Resolution::has_width_offset() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Resolution::set_has_width_offset() {
  _has_bits_[0] |= 0x00000004u;
}
void Resolution::clear_has_width_offset() {
  _has_bits_[0] &= ~0x00000004u;
}
void Resolution::clear_width_offset() {
  width_offset_ = 0u;
  clear_has_width_offset();
}
 ::google::protobuf::uint32 Resolution::width_offset() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Resolution.width_offset)
  return width_offset_;
}
 void Resolution::set_width_offset(::google::protobuf::uint32 value) {
  set_has_width_offset();
  width_offset_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Resolution.width_offset)
}

// required uint32 height_offset = 4;
bool Resolution::has_height_offset() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Resolution::set_has_height_offset() {
  _has_bits_[0] |= 0x00000008u;
}
void Resolution::clear_has_height_offset() {
  _has_bits_[0] &= ~0x00000008u;
}
void Resolution::clear_height_offset() {
  height_offset_ = 0u;
  clear_has_height_offset();
}
 ::google::protobuf::uint32 Resolution::height_offset() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Resolution.height_offset)
  return height_offset_;
}
 void Resolution::set_height_offset(::google::protobuf::uint32 value) {
  set_has_height_offset();
  height_offset_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Resolution.height_offset)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Camera::kCameraNameFieldNumber;
const int Camera::kCameraTypeFieldNumber;
const int Camera::kCameraPathFieldNumber;
const int Camera::kCameraMatrixFieldNumber;
const int Camera::kCameraDistortionFieldNumber;
const int Camera::kFpsFieldNumber;
const int Camera::kResolutionFieldNumber;
const int Camera::kAutoExposureFieldNumber;
const int Camera::kExposureValueFieldNumber;
const int Camera::kExposureTimeFieldNumber;
const int Camera::kAutoWhiteBalanceFieldNumber;
const int Camera::kAutoGainFieldNumber;
const int Camera::kContrastFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Camera::Camera()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_camera.Camera)
}

void Camera::InitAsDefaultInstance() {
  camera_matrix_ = const_cast< ::roborts_camera::CameraMatrix*>(&::roborts_camera::CameraMatrix::default_instance());
  camera_distortion_ = const_cast< ::roborts_camera::CameraDistortion*>(&::roborts_camera::CameraDistortion::default_instance());
  resolution_ = const_cast< ::roborts_camera::Resolution*>(&::roborts_camera::Resolution::default_instance());
}

Camera::Camera(const Camera& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_camera.Camera)
}

void Camera::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  camera_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_matrix_ = NULL;
  camera_distortion_ = NULL;
  fps_ = 0u;
  resolution_ = NULL;
  auto_exposure_ = false;
  exposure_value_ = 0u;
  exposure_time_ = 0u;
  auto_white_balance_ = false;
  auto_gain_ = false;
  contrast_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Camera::~Camera() {
  // @@protoc_insertion_point(destructor:roborts_camera.Camera)
  SharedDtor();
}

void Camera::SharedDtor() {
  camera_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  camera_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete camera_matrix_;
    delete camera_distortion_;
    delete resolution_;
  }
}

void Camera::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Camera::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Camera_descriptor_;
}

const Camera& Camera::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fparam_2eproto();
  return *default_instance_;
}

Camera* Camera::default_instance_ = NULL;

Camera* Camera::New(::google::protobuf::Arena* arena) const {
  Camera* n = new Camera;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Camera::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_camera.Camera)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Camera, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Camera*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    if (has_camera_name()) {
      camera_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_camera_type()) {
      camera_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_camera_path()) {
      camera_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_camera_matrix()) {
      if (camera_matrix_ != NULL) camera_matrix_->::roborts_camera::CameraMatrix::Clear();
    }
    if (has_camera_distortion()) {
      if (camera_distortion_ != NULL) camera_distortion_->::roborts_camera::CameraDistortion::Clear();
    }
    fps_ = 0u;
    if (has_resolution()) {
      if (resolution_ != NULL) resolution_->::roborts_camera::Resolution::Clear();
    }
    auto_exposure_ = false;
  }
  if (_has_bits_[8 / 32] & 7936u) {
    ZR_(exposure_value_, exposure_time_);
    ZR_(auto_white_balance_, contrast_);
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Camera::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_camera.Camera)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string camera_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camera_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->camera_name().data(), this->camera_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_camera.Camera.camera_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_camera_type;
        break;
      }

      // required string camera_type = 2;
      case 2: {
        if (tag == 18) {
         parse_camera_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camera_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->camera_type().data(), this->camera_type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_camera.Camera.camera_type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_camera_path;
        break;
      }

      // required string camera_path = 3;
      case 3: {
        if (tag == 26) {
         parse_camera_path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camera_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->camera_path().data(), this->camera_path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "roborts_camera.Camera.camera_path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_camera_matrix;
        break;
      }

      // required .roborts_camera.CameraMatrix camera_matrix = 4;
      case 4: {
        if (tag == 34) {
         parse_camera_matrix:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_camera_matrix()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_camera_distortion;
        break;
      }

      // required .roborts_camera.CameraDistortion camera_distortion = 5;
      case 5: {
        if (tag == 42) {
         parse_camera_distortion:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_camera_distortion()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_fps;
        break;
      }

      // optional uint32 fps = 6;
      case 6: {
        if (tag == 48) {
         parse_fps:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fps_)));
          set_has_fps();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_resolution;
        break;
      }

      // optional .roborts_camera.Resolution resolution = 7;
      case 7: {
        if (tag == 58) {
         parse_resolution:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_resolution()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_auto_exposure;
        break;
      }

      // optional bool auto_exposure = 8;
      case 8: {
        if (tag == 64) {
         parse_auto_exposure:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auto_exposure_)));
          set_has_auto_exposure();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_exposure_value;
        break;
      }

      // optional uint32 exposure_value = 9;
      case 9: {
        if (tag == 72) {
         parse_exposure_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &exposure_value_)));
          set_has_exposure_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_exposure_time;
        break;
      }

      // optional uint32 exposure_time = 10;
      case 10: {
        if (tag == 80) {
         parse_exposure_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &exposure_time_)));
          set_has_exposure_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_auto_white_balance;
        break;
      }

      // optional bool auto_white_balance = 11;
      case 11: {
        if (tag == 88) {
         parse_auto_white_balance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auto_white_balance_)));
          set_has_auto_white_balance();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_auto_gain;
        break;
      }

      // optional bool auto_gain = 12;
      case 12: {
        if (tag == 96) {
         parse_auto_gain:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auto_gain_)));
          set_has_auto_gain();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_contrast;
        break;
      }

      // optional uint32 contrast = 13;
      case 13: {
        if (tag == 104) {
         parse_contrast:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &contrast_)));
          set_has_contrast();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_camera.Camera)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_camera.Camera)
  return false;
#undef DO_
}

void Camera::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_camera.Camera)
  // required string camera_name = 1;
  if (has_camera_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_name().data(), this->camera_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->camera_name(), output);
  }

  // required string camera_type = 2;
  if (has_camera_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_type().data(), this->camera_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->camera_type(), output);
  }

  // required string camera_path = 3;
  if (has_camera_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_path().data(), this->camera_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->camera_path(), output);
  }

  // required .roborts_camera.CameraMatrix camera_matrix = 4;
  if (has_camera_matrix()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->camera_matrix_, output);
  }

  // required .roborts_camera.CameraDistortion camera_distortion = 5;
  if (has_camera_distortion()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->camera_distortion_, output);
  }

  // optional uint32 fps = 6;
  if (has_fps()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->fps(), output);
  }

  // optional .roborts_camera.Resolution resolution = 7;
  if (has_resolution()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->resolution_, output);
  }

  // optional bool auto_exposure = 8;
  if (has_auto_exposure()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->auto_exposure(), output);
  }

  // optional uint32 exposure_value = 9;
  if (has_exposure_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->exposure_value(), output);
  }

  // optional uint32 exposure_time = 10;
  if (has_exposure_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->exposure_time(), output);
  }

  // optional bool auto_white_balance = 11;
  if (has_auto_white_balance()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->auto_white_balance(), output);
  }

  // optional bool auto_gain = 12;
  if (has_auto_gain()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->auto_gain(), output);
  }

  // optional uint32 contrast = 13;
  if (has_contrast()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(13, this->contrast(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_camera.Camera)
}

::google::protobuf::uint8* Camera::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_camera.Camera)
  // required string camera_name = 1;
  if (has_camera_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_name().data(), this->camera_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->camera_name(), target);
  }

  // required string camera_type = 2;
  if (has_camera_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_type().data(), this->camera_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->camera_type(), target);
  }

  // required string camera_path = 3;
  if (has_camera_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->camera_path().data(), this->camera_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "roborts_camera.Camera.camera_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->camera_path(), target);
  }

  // required .roborts_camera.CameraMatrix camera_matrix = 4;
  if (has_camera_matrix()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->camera_matrix_, false, target);
  }

  // required .roborts_camera.CameraDistortion camera_distortion = 5;
  if (has_camera_distortion()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->camera_distortion_, false, target);
  }

  // optional uint32 fps = 6;
  if (has_fps()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->fps(), target);
  }

  // optional .roborts_camera.Resolution resolution = 7;
  if (has_resolution()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->resolution_, false, target);
  }

  // optional bool auto_exposure = 8;
  if (has_auto_exposure()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->auto_exposure(), target);
  }

  // optional uint32 exposure_value = 9;
  if (has_exposure_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->exposure_value(), target);
  }

  // optional uint32 exposure_time = 10;
  if (has_exposure_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->exposure_time(), target);
  }

  // optional bool auto_white_balance = 11;
  if (has_auto_white_balance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->auto_white_balance(), target);
  }

  // optional bool auto_gain = 12;
  if (has_auto_gain()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->auto_gain(), target);
  }

  // optional uint32 contrast = 13;
  if (has_contrast()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(13, this->contrast(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_camera.Camera)
  return target;
}

int Camera::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:roborts_camera.Camera)
  int total_size = 0;

  if (has_camera_name()) {
    // required string camera_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_name());
  }

  if (has_camera_type()) {
    // required string camera_type = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_type());
  }

  if (has_camera_path()) {
    // required string camera_path = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_path());
  }

  if (has_camera_matrix()) {
    // required .roborts_camera.CameraMatrix camera_matrix = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->camera_matrix_);
  }

  if (has_camera_distortion()) {
    // required .roborts_camera.CameraDistortion camera_distortion = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->camera_distortion_);
  }

  return total_size;
}
int Camera::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_camera.Camera)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required string camera_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_name());

    // required string camera_type = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_type());

    // required string camera_path = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->camera_path());

    // required .roborts_camera.CameraMatrix camera_matrix = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->camera_matrix_);

    // required .roborts_camera.CameraDistortion camera_distortion = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->camera_distortion_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[5 / 32] & 224u) {
    // optional uint32 fps = 6;
    if (has_fps()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->fps());
    }

    // optional .roborts_camera.Resolution resolution = 7;
    if (has_resolution()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->resolution_);
    }

    // optional bool auto_exposure = 8;
    if (has_auto_exposure()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & 7936u) {
    // optional uint32 exposure_value = 9;
    if (has_exposure_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->exposure_value());
    }

    // optional uint32 exposure_time = 10;
    if (has_exposure_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->exposure_time());
    }

    // optional bool auto_white_balance = 11;
    if (has_auto_white_balance()) {
      total_size += 1 + 1;
    }

    // optional bool auto_gain = 12;
    if (has_auto_gain()) {
      total_size += 1 + 1;
    }

    // optional uint32 contrast = 13;
    if (has_contrast()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->contrast());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Camera::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_camera.Camera)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Camera* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Camera>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_camera.Camera)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_camera.Camera)
    MergeFrom(*source);
  }
}

void Camera::MergeFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_camera.Camera)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_camera_name()) {
      set_has_camera_name();
      camera_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camera_name_);
    }
    if (from.has_camera_type()) {
      set_has_camera_type();
      camera_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camera_type_);
    }
    if (from.has_camera_path()) {
      set_has_camera_path();
      camera_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.camera_path_);
    }
    if (from.has_camera_matrix()) {
      mutable_camera_matrix()->::roborts_camera::CameraMatrix::MergeFrom(from.camera_matrix());
    }
    if (from.has_camera_distortion()) {
      mutable_camera_distortion()->::roborts_camera::CameraDistortion::MergeFrom(from.camera_distortion());
    }
    if (from.has_fps()) {
      set_fps(from.fps());
    }
    if (from.has_resolution()) {
      mutable_resolution()->::roborts_camera::Resolution::MergeFrom(from.resolution());
    }
    if (from.has_auto_exposure()) {
      set_auto_exposure(from.auto_exposure());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_exposure_value()) {
      set_exposure_value(from.exposure_value());
    }
    if (from.has_exposure_time()) {
      set_exposure_time(from.exposure_time());
    }
    if (from.has_auto_white_balance()) {
      set_auto_white_balance(from.auto_white_balance());
    }
    if (from.has_auto_gain()) {
      set_auto_gain(from.auto_gain());
    }
    if (from.has_contrast()) {
      set_contrast(from.contrast());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Camera::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_camera.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Camera::CopyFrom(const Camera& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_camera.Camera)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Camera::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  if (has_resolution()) {
    if (!this->resolution_->IsInitialized()) return false;
  }
  return true;
}

void Camera::Swap(Camera* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Camera::InternalSwap(Camera* other) {
  camera_name_.Swap(&other->camera_name_);
  camera_type_.Swap(&other->camera_type_);
  camera_path_.Swap(&other->camera_path_);
  std::swap(camera_matrix_, other->camera_matrix_);
  std::swap(camera_distortion_, other->camera_distortion_);
  std::swap(fps_, other->fps_);
  std::swap(resolution_, other->resolution_);
  std::swap(auto_exposure_, other->auto_exposure_);
  std::swap(exposure_value_, other->exposure_value_);
  std::swap(exposure_time_, other->exposure_time_);
  std::swap(auto_white_balance_, other->auto_white_balance_);
  std::swap(auto_gain_, other->auto_gain_);
  std::swap(contrast_, other->contrast_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Camera::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Camera_descriptor_;
  metadata.reflection = Camera_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Camera

// required string camera_name = 1;
bool Camera::has_camera_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Camera::set_has_camera_name() {
  _has_bits_[0] |= 0x00000001u;
}
void Camera::clear_has_camera_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void Camera::clear_camera_name() {
  camera_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_name();
}
 const ::std::string& Camera::camera_name() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.camera_name)
  return camera_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_camera_name(const ::std::string& value) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.camera_name)
}
 void Camera::set_camera_name(const char* value) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_camera.Camera.camera_name)
}
 void Camera::set_camera_name(const char* value, size_t size) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_camera.Camera.camera_name)
}
 ::std::string* Camera::mutable_camera_name() {
  set_has_camera_name();
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.camera_name)
  return camera_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Camera::release_camera_name() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.camera_name)
  clear_has_camera_name();
  return camera_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_allocated_camera_name(::std::string* camera_name) {
  if (camera_name != NULL) {
    set_has_camera_name();
  } else {
    clear_has_camera_name();
  }
  camera_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_name);
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.camera_name)
}

// required string camera_type = 2;
bool Camera::has_camera_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Camera::set_has_camera_type() {
  _has_bits_[0] |= 0x00000002u;
}
void Camera::clear_has_camera_type() {
  _has_bits_[0] &= ~0x00000002u;
}
void Camera::clear_camera_type() {
  camera_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_type();
}
 const ::std::string& Camera::camera_type() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.camera_type)
  return camera_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_camera_type(const ::std::string& value) {
  set_has_camera_type();
  camera_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.camera_type)
}
 void Camera::set_camera_type(const char* value) {
  set_has_camera_type();
  camera_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_camera.Camera.camera_type)
}
 void Camera::set_camera_type(const char* value, size_t size) {
  set_has_camera_type();
  camera_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_camera.Camera.camera_type)
}
 ::std::string* Camera::mutable_camera_type() {
  set_has_camera_type();
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.camera_type)
  return camera_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Camera::release_camera_type() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.camera_type)
  clear_has_camera_type();
  return camera_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_allocated_camera_type(::std::string* camera_type) {
  if (camera_type != NULL) {
    set_has_camera_type();
  } else {
    clear_has_camera_type();
  }
  camera_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_type);
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.camera_type)
}

// required string camera_path = 3;
bool Camera::has_camera_path() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Camera::set_has_camera_path() {
  _has_bits_[0] |= 0x00000004u;
}
void Camera::clear_has_camera_path() {
  _has_bits_[0] &= ~0x00000004u;
}
void Camera::clear_camera_path() {
  camera_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_path();
}
 const ::std::string& Camera::camera_path() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.camera_path)
  return camera_path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_camera_path(const ::std::string& value) {
  set_has_camera_path();
  camera_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.camera_path)
}
 void Camera::set_camera_path(const char* value) {
  set_has_camera_path();
  camera_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_camera.Camera.camera_path)
}
 void Camera::set_camera_path(const char* value, size_t size) {
  set_has_camera_path();
  camera_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_camera.Camera.camera_path)
}
 ::std::string* Camera::mutable_camera_path() {
  set_has_camera_path();
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.camera_path)
  return camera_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Camera::release_camera_path() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.camera_path)
  clear_has_camera_path();
  return camera_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Camera::set_allocated_camera_path(::std::string* camera_path) {
  if (camera_path != NULL) {
    set_has_camera_path();
  } else {
    clear_has_camera_path();
  }
  camera_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_path);
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.camera_path)
}

// required .roborts_camera.CameraMatrix camera_matrix = 4;
bool Camera::has_camera_matrix() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Camera::set_has_camera_matrix() {
  _has_bits_[0] |= 0x00000008u;
}
void Camera::clear_has_camera_matrix() {
  _has_bits_[0] &= ~0x00000008u;
}
void Camera::clear_camera_matrix() {
  if (camera_matrix_ != NULL) camera_matrix_->::roborts_camera::CameraMatrix::Clear();
  clear_has_camera_matrix();
}
const ::roborts_camera::CameraMatrix& Camera::camera_matrix() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.camera_matrix)
  return camera_matrix_ != NULL ? *camera_matrix_ : *default_instance_->camera_matrix_;
}
::roborts_camera::CameraMatrix* Camera::mutable_camera_matrix() {
  set_has_camera_matrix();
  if (camera_matrix_ == NULL) {
    camera_matrix_ = new ::roborts_camera::CameraMatrix;
  }
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.camera_matrix)
  return camera_matrix_;
}
::roborts_camera::CameraMatrix* Camera::release_camera_matrix() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.camera_matrix)
  clear_has_camera_matrix();
  ::roborts_camera::CameraMatrix* temp = camera_matrix_;
  camera_matrix_ = NULL;
  return temp;
}
void Camera::set_allocated_camera_matrix(::roborts_camera::CameraMatrix* camera_matrix) {
  delete camera_matrix_;
  camera_matrix_ = camera_matrix;
  if (camera_matrix) {
    set_has_camera_matrix();
  } else {
    clear_has_camera_matrix();
  }
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.camera_matrix)
}

// required .roborts_camera.CameraDistortion camera_distortion = 5;
bool Camera::has_camera_distortion() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Camera::set_has_camera_distortion() {
  _has_bits_[0] |= 0x00000010u;
}
void Camera::clear_has_camera_distortion() {
  _has_bits_[0] &= ~0x00000010u;
}
void Camera::clear_camera_distortion() {
  if (camera_distortion_ != NULL) camera_distortion_->::roborts_camera::CameraDistortion::Clear();
  clear_has_camera_distortion();
}
const ::roborts_camera::CameraDistortion& Camera::camera_distortion() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.camera_distortion)
  return camera_distortion_ != NULL ? *camera_distortion_ : *default_instance_->camera_distortion_;
}
::roborts_camera::CameraDistortion* Camera::mutable_camera_distortion() {
  set_has_camera_distortion();
  if (camera_distortion_ == NULL) {
    camera_distortion_ = new ::roborts_camera::CameraDistortion;
  }
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.camera_distortion)
  return camera_distortion_;
}
::roborts_camera::CameraDistortion* Camera::release_camera_distortion() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.camera_distortion)
  clear_has_camera_distortion();
  ::roborts_camera::CameraDistortion* temp = camera_distortion_;
  camera_distortion_ = NULL;
  return temp;
}
void Camera::set_allocated_camera_distortion(::roborts_camera::CameraDistortion* camera_distortion) {
  delete camera_distortion_;
  camera_distortion_ = camera_distortion;
  if (camera_distortion) {
    set_has_camera_distortion();
  } else {
    clear_has_camera_distortion();
  }
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.camera_distortion)
}

// optional uint32 fps = 6;
bool Camera::has_fps() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Camera::set_has_fps() {
  _has_bits_[0] |= 0x00000020u;
}
void Camera::clear_has_fps() {
  _has_bits_[0] &= ~0x00000020u;
}
void Camera::clear_fps() {
  fps_ = 0u;
  clear_has_fps();
}
 ::google::protobuf::uint32 Camera::fps() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.fps)
  return fps_;
}
 void Camera::set_fps(::google::protobuf::uint32 value) {
  set_has_fps();
  fps_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.fps)
}

// optional .roborts_camera.Resolution resolution = 7;
bool Camera::has_resolution() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void Camera::set_has_resolution() {
  _has_bits_[0] |= 0x00000040u;
}
void Camera::clear_has_resolution() {
  _has_bits_[0] &= ~0x00000040u;
}
void Camera::clear_resolution() {
  if (resolution_ != NULL) resolution_->::roborts_camera::Resolution::Clear();
  clear_has_resolution();
}
const ::roborts_camera::Resolution& Camera::resolution() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.resolution)
  return resolution_ != NULL ? *resolution_ : *default_instance_->resolution_;
}
::roborts_camera::Resolution* Camera::mutable_resolution() {
  set_has_resolution();
  if (resolution_ == NULL) {
    resolution_ = new ::roborts_camera::Resolution;
  }
  // @@protoc_insertion_point(field_mutable:roborts_camera.Camera.resolution)
  return resolution_;
}
::roborts_camera::Resolution* Camera::release_resolution() {
  // @@protoc_insertion_point(field_release:roborts_camera.Camera.resolution)
  clear_has_resolution();
  ::roborts_camera::Resolution* temp = resolution_;
  resolution_ = NULL;
  return temp;
}
void Camera::set_allocated_resolution(::roborts_camera::Resolution* resolution) {
  delete resolution_;
  resolution_ = resolution;
  if (resolution) {
    set_has_resolution();
  } else {
    clear_has_resolution();
  }
  // @@protoc_insertion_point(field_set_allocated:roborts_camera.Camera.resolution)
}

// optional bool auto_exposure = 8;
bool Camera::has_auto_exposure() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void Camera::set_has_auto_exposure() {
  _has_bits_[0] |= 0x00000080u;
}
void Camera::clear_has_auto_exposure() {
  _has_bits_[0] &= ~0x00000080u;
}
void Camera::clear_auto_exposure() {
  auto_exposure_ = false;
  clear_has_auto_exposure();
}
 bool Camera::auto_exposure() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.auto_exposure)
  return auto_exposure_;
}
 void Camera::set_auto_exposure(bool value) {
  set_has_auto_exposure();
  auto_exposure_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.auto_exposure)
}

// optional uint32 exposure_value = 9;
bool Camera::has_exposure_value() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void Camera::set_has_exposure_value() {
  _has_bits_[0] |= 0x00000100u;
}
void Camera::clear_has_exposure_value() {
  _has_bits_[0] &= ~0x00000100u;
}
void Camera::clear_exposure_value() {
  exposure_value_ = 0u;
  clear_has_exposure_value();
}
 ::google::protobuf::uint32 Camera::exposure_value() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.exposure_value)
  return exposure_value_;
}
 void Camera::set_exposure_value(::google::protobuf::uint32 value) {
  set_has_exposure_value();
  exposure_value_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.exposure_value)
}

// optional uint32 exposure_time = 10;
bool Camera::has_exposure_time() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void Camera::set_has_exposure_time() {
  _has_bits_[0] |= 0x00000200u;
}
void Camera::clear_has_exposure_time() {
  _has_bits_[0] &= ~0x00000200u;
}
void Camera::clear_exposure_time() {
  exposure_time_ = 0u;
  clear_has_exposure_time();
}
 ::google::protobuf::uint32 Camera::exposure_time() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.exposure_time)
  return exposure_time_;
}
 void Camera::set_exposure_time(::google::protobuf::uint32 value) {
  set_has_exposure_time();
  exposure_time_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.exposure_time)
}

// optional bool auto_white_balance = 11;
bool Camera::has_auto_white_balance() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void Camera::set_has_auto_white_balance() {
  _has_bits_[0] |= 0x00000400u;
}
void Camera::clear_has_auto_white_balance() {
  _has_bits_[0] &= ~0x00000400u;
}
void Camera::clear_auto_white_balance() {
  auto_white_balance_ = false;
  clear_has_auto_white_balance();
}
 bool Camera::auto_white_balance() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.auto_white_balance)
  return auto_white_balance_;
}
 void Camera::set_auto_white_balance(bool value) {
  set_has_auto_white_balance();
  auto_white_balance_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.auto_white_balance)
}

// optional bool auto_gain = 12;
bool Camera::has_auto_gain() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void Camera::set_has_auto_gain() {
  _has_bits_[0] |= 0x00000800u;
}
void Camera::clear_has_auto_gain() {
  _has_bits_[0] &= ~0x00000800u;
}
void Camera::clear_auto_gain() {
  auto_gain_ = false;
  clear_has_auto_gain();
}
 bool Camera::auto_gain() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.auto_gain)
  return auto_gain_;
}
 void Camera::set_auto_gain(bool value) {
  set_has_auto_gain();
  auto_gain_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.auto_gain)
}

// optional uint32 contrast = 13;
bool Camera::has_contrast() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void Camera::set_has_contrast() {
  _has_bits_[0] |= 0x00001000u;
}
void Camera::clear_has_contrast() {
  _has_bits_[0] &= ~0x00001000u;
}
void Camera::clear_contrast() {
  contrast_ = 0u;
  clear_has_contrast();
}
 ::google::protobuf::uint32 Camera::contrast() const {
  // @@protoc_insertion_point(field_get:roborts_camera.Camera.contrast)
  return contrast_;
}
 void Camera::set_contrast(::google::protobuf::uint32 value) {
  set_has_contrast();
  contrast_ = value;
  // @@protoc_insertion_point(field_set:roborts_camera.Camera.contrast)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cameras::kCameraFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cameras::Cameras()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:roborts_camera.Cameras)
}

void Cameras::InitAsDefaultInstance() {
}

Cameras::Cameras(const Cameras& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:roborts_camera.Cameras)
}

void Cameras::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Cameras::~Cameras() {
  // @@protoc_insertion_point(destructor:roborts_camera.Cameras)
  SharedDtor();
}

void Cameras::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Cameras::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cameras::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Cameras_descriptor_;
}

const Cameras& Cameras::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fparam_2eproto();
  return *default_instance_;
}

Cameras* Cameras::default_instance_ = NULL;

Cameras* Cameras::New(::google::protobuf::Arena* arena) const {
  Cameras* n = new Cameras;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cameras::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_camera.Cameras)
  camera_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Cameras::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:roborts_camera.Cameras)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .roborts_camera.Camera camera = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_camera:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_camera()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_camera;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:roborts_camera.Cameras)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:roborts_camera.Cameras)
  return false;
#undef DO_
}

void Cameras::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:roborts_camera.Cameras)
  // repeated .roborts_camera.Camera camera = 1;
  for (unsigned int i = 0, n = this->camera_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->camera(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:roborts_camera.Cameras)
}

::google::protobuf::uint8* Cameras::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_camera.Cameras)
  // repeated .roborts_camera.Camera camera = 1;
  for (unsigned int i = 0, n = this->camera_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->camera(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_camera.Cameras)
  return target;
}

int Cameras::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_camera.Cameras)
  int total_size = 0;

  // repeated .roborts_camera.Camera camera = 1;
  total_size += 1 * this->camera_size();
  for (int i = 0; i < this->camera_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->camera(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Cameras::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:roborts_camera.Cameras)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Cameras* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Cameras>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:roborts_camera.Cameras)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:roborts_camera.Cameras)
    MergeFrom(*source);
  }
}

void Cameras::MergeFrom(const Cameras& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:roborts_camera.Cameras)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  camera_.MergeFrom(from.camera_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Cameras::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:roborts_camera.Cameras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Cameras::CopyFrom(const Cameras& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_camera.Cameras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Cameras::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->camera())) return false;
  return true;
}

void Cameras::Swap(Cameras* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cameras::InternalSwap(Cameras* other) {
  camera_.UnsafeArenaSwap(&other->camera_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Cameras::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Cameras_descriptor_;
  metadata.reflection = Cameras_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Cameras

// repeated .roborts_camera.Camera camera = 1;
int Cameras::camera_size() const {
  return camera_.size();
}
void Cameras::clear_camera() {
  camera_.Clear();
}
const ::roborts_camera::Camera& Cameras::camera(int index) const {
  // @@protoc_insertion_point(field_get:roborts_camera.Cameras.camera)
  return camera_.Get(index);
}
::roborts_camera::Camera* Cameras::mutable_camera(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_camera.Cameras.camera)
  return camera_.Mutable(index);
}
::roborts_camera::Camera* Cameras::add_camera() {
  // @@protoc_insertion_point(field_add:roborts_camera.Cameras.camera)
  return camera_.Add();
}
::google::protobuf::RepeatedPtrField< ::roborts_camera::Camera >*
Cameras::mutable_camera() {
  // @@protoc_insertion_point(field_mutable_list:roborts_camera.Cameras.camera)
  return &camera_;
}
const ::google::protobuf::RepeatedPtrField< ::roborts_camera::Camera >&
Cameras::camera() const {
  // @@protoc_insertion_point(field_list:roborts_camera.Cameras.camera)
  return camera_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_camera

// @@protoc_insertion_point(global_scope)
